name: RNE
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.16
  - pip
  - pip:
      - --find-links https://download.pytorch.org/whl/torch_stable.html
      - --requirement requirements.txt
